spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: test1
      auto-index-creation: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

jwtSecret: obUDzHwWI9vbRJmqop8HxFINlOhdUQQC3NCrU16DWd4
jwtExpirationMs: 86400000